### ISSUE TITLE
Input lat/long instead of hardcoded location

### ISSUE THREAD

**Issue by pavelmoulisjr** [Novalys/Pokemon-Go-Rocket-API#4] opened 2016-07-21 08:40 UTC
Current hardcoded location (64-65 MainForm.cs), replace with temporary lat/long input until I create a draggable map.

**Comment by Novalys** [comment] 2016-07-21 08:42
The plan was to add Google Maps support #1 eventually, for now I hard coded that location since it's a good spot in London :smile:

**Comment by pavelmoulisjr** [comment] 2016-07-21 08:45
Oh awkward, completely missed that. Nice, nice! 

:laughing:

**Comment by Novalys** [comment] 2016-07-21 08:50
Duplicate of #1

**Closed by Novalys** 2016-07-21 08:50 UTC
